[package]
name = "dhcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

fp_core = { path = "../fp_core" }
chrono = "0.4.24"
mac_address  = "1.1.4"
itertools = "0.10.5"
byteorder = "1.4.3"
